#ifndef DT_ERR_H
#define DT_ERR_H

typedef enum {
  DT_ERR_OK = 0,
  DT_ERR_FLASHMEMSIZE = 1,
  DT_ERR_INVALIDKEY = 2,
  DT_ERR_CORRUPT = 3,
  DT_ERR_MALLOC = 4,
  DT_ERR_VALSIZE = 5,
  DT_ERR_KEYNOTFOUND = 6,
  DT_ERR_MACADDR = 7,
  DT_ERR_LWIPERR = 8,
  DT_ERR_OPENSERVER = 9,
  DT_ERR_I2CINIT = 10,
} DT_ERR_E;

#endif
